# Generated by Django 5.1 on 2026-03-25 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='프로젝트명')),
                ('description', models.TextField(verbose_name='설명')),
                ('difficulty', models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], default='intermediate', max_length=20, verbose_name='난이도')),
                ('estimated_hours', models.IntegerField(default=0, verbose_name='예상 소요 시간')),
                ('tech_stack', models.JSONField(default=list, verbose_name='기술 스택')),
                ('learning_objectives', models.JSONField(default=list, verbose_name='학습 목표')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='썸네일 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '프로젝트',
                'verbose_name_plural': '프로젝트 목록',
                'db_table': 'projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['difficulty', 'is_active'], name='projects_difficu_137bcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('planning', '계획 중'), ('in_progress', '진행 중'), ('completed', '완료'), ('paused', '일시 중지')], default='planning', max_length=20, verbose_name='상태')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('demo_url', models.URLField(blank=True, verbose_name='데모 URL')),
                ('started_at', models.DateField(blank=True, null=True, verbose_name='시작일')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='완료일')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_projects', to='project.project', verbose_name='프로젝트 템플릿')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로젝트',
                'verbose_name_plural': '사용자 프로젝트 목록',
                'db_table': 'user_projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='user_projec_user_id_b4e100_idx')],
            },
        ),
    ]
