# Generated by Django 5.1 on 2026-03-25 13:37

import common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPathTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.CharField(max_length=200, unique=True, verbose_name='템플릿 키')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('category', models.CharField(choices=[('job', '직업'), ('high_school', '고등학교'), ('university', '대학교'), ('general', '일반')], default='general', max_length=50, verbose_name='카테고리')),
                ('job_id', models.CharField(blank=True, max_length=100, verbose_name='연결된 직업 ID')),
                ('university_id', models.CharField(blank=True, max_length=100, verbose_name='연결된 대학 ID')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('uses', models.IntegerField(default=0, verbose_name='사용 횟수')),
                ('is_official', models.BooleanField(default=False, verbose_name='공식 템플릿 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '커리어 패스 템플릿',
                'verbose_name_plural': '커리어 패스 템플릿 목록',
                'db_table': 'career_path_templates',
                'ordering': ['-is_official', '-likes', '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='career_path_categor_f04df5_idx'), models.Index(fields=['job_id'], name='career_path_job_id_1f9b0b_idx'), models.Index(fields=['university_id'], name='career_path_univers_30f28b_idx'), models.Index(fields=['-likes'], name='career_path_likes_ab93a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='학교명')),
                ('school_type', models.CharField(choices=[('elementary', '초등학교'), ('middle', '중학교'), ('high', '고등학교'), ('university', '대학교'), ('academy', '학원'), ('other', '기타')], max_length=50, verbose_name='학교 유형')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='위치')),
                ('invite_code', models.CharField(default=common.utils.generate_invite_code, max_length=20, unique=True, verbose_name='초대 코드')),
                ('member_count', models.IntegerField(default=0, verbose_name='멤버 수')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증 여부')),
            ],
            options={
                'verbose_name': '학교',
                'verbose_name_plural': '학교 목록',
                'db_table': 'schools',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['school_type'], name='schools_school__eef8c2_idx'), models.Index(fields=['invite_code'], name='schools_invite__9fa426_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=50, verbose_name='연도')),
                ('order_index', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='career_path.careerpathtemplate', verbose_name='템플릿')),
            ],
            options={
                'verbose_name': '템플릿 연도',
                'verbose_name_plural': '템플릿 연도 목록',
                'db_table': 'template_years',
                'ordering': ['template', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('activity', '활동'), ('study', '학습'), ('competition', '대회'), ('project', '프로젝트'), ('certification', '자격증'), ('other', '기타')], default='activity', max_length=50, verbose_name='항목 유형')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='월')),
                ('emoji', models.CharField(default='📌', max_length=10, verbose_name='이모지')),
                ('order_index', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='career_path.templateyear', verbose_name='연도')),
            ],
            options={
                'verbose_name': '템플릿 항목',
                'verbose_name_plural': '템플릿 항목 목록',
                'db_table': 'template_items',
                'ordering': ['year', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='UserCareerPath',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('planning', '계획 중'), ('in_progress', '진행 중'), ('completed', '완료'), ('paused', '일시 중지')], default='planning', max_length=20, verbose_name='상태')),
                ('share_scope', models.CharField(choices=[('private', '비공개'), ('school', '학교 공개'), ('group', '그룹 공개'), ('public', '전체 공개')], default='private', max_length=20, verbose_name='공유 범위')),
                ('path_data', models.JSONField(default=dict, verbose_name='패스 데이터')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='진행률')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_paths', to='career_path.careerpathtemplate', verbose_name='기반 템플릿')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 커리어 패스',
                'verbose_name_plural': '사용자 커리어 패스 목록',
                'db_table': 'user_career_paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('student', '학생'), ('teacher', '선생님'), ('admin', '관리자')], default='student', max_length=20, verbose_name='역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='career_path.school', verbose_name='학교')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '학교 멤버',
                'verbose_name_plural': '학교 멤버 목록',
                'db_table': 'school_members',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['school', 'role'], name='school_memb_school__a8f7a6_idx'), models.Index(fields=['user'], name='school_memb_user_id_8bd3cc_idx')],
                'unique_together': {('school', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='templateyear',
            index=models.Index(fields=['template', 'order_index'], name='template_ye_templat_5861b7_idx'),
        ),
        migrations.AddIndex(
            model_name='templateitem',
            index=models.Index(fields=['year', 'order_index'], name='template_it_year_id_bdc290_idx'),
        ),
        migrations.AddIndex(
            model_name='templateitem',
            index=models.Index(fields=['item_type'], name='template_it_item_ty_8c7ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='usercareerpath',
            index=models.Index(fields=['user', '-created_at'], name='user_career_user_id_bfda79_idx'),
        ),
        migrations.AddIndex(
            model_name='usercareerpath',
            index=models.Index(fields=['template'], name='user_career_templat_8471f4_idx'),
        ),
        migrations.AddIndex(
            model_name='usercareerpath',
            index=models.Index(fields=['status'], name='user_career_status_9d84ef_idx'),
        ),
        migrations.AddIndex(
            model_name='usercareerpath',
            index=models.Index(fields=['share_scope'], name='user_career_share_s_f349e0_idx'),
        ),
    ]
