# Generated by Django 5.2.5 on 2026-03-27 02:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_path", "0001_initial"),
        ("community", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="커리어 패스 제목"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="커리어 패스 설명"
                    ),
                ),
                ("job_id", models.CharField(max_length=100, verbose_name="직업 ID")),
                (
                    "job_name",
                    models.CharField(max_length=100, verbose_name="직업 이름"),
                ),
                (
                    "job_emoji",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="직업 이모지"
                    ),
                ),
                ("star_id", models.CharField(max_length=100, verbose_name="적성 ID")),
                (
                    "star_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="적성 이름"
                    ),
                ),
                (
                    "star_emoji",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="적성 이모지"
                    ),
                ),
                (
                    "star_color",
                    models.CharField(
                        default="#6C5CE7", max_length=20, verbose_name="적성 색상"
                    ),
                ),
                (
                    "is_template",
                    models.BooleanField(default=False, verbose_name="템플릿 여부"),
                ),
                (
                    "template_category",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="템플릿 카테고리",
                    ),
                ),
            ],
            options={
                "verbose_name": "커리어 패스",
                "verbose_name_plural": "커리어 패스 목록",
                "db_table": "career_path_career_plans",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoalGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("goal", models.TextField(verbose_name="목표")),
                (
                    "semester_id",
                    models.CharField(
                        blank=True,
                        choices=[("first", "1학기"), ("second", "2학기"), ("", "통합")],
                        default="",
                        max_length=20,
                        verbose_name="학기 구분",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="정렬 순서"),
                ),
            ],
            options={
                "verbose_name": "목표 그룹",
                "verbose_name_plural": "목표 그룹 목록",
                "db_table": "career_path_goal_groups",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ItemLink",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="링크 제목")),
                ("url", models.URLField(verbose_name="링크 URL")),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("official", "공식 사이트"),
                            ("application", "신청 페이지"),
                            ("reference", "참고 자료"),
                            ("portfolio", "포트폴리오"),
                            ("result", "결과물"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="링크 종류",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="정렬 순서"),
                ),
            ],
            options={
                "verbose_name": "활동 참고 링크",
                "verbose_name_plural": "활동 참고 링크 목록",
                "db_table": "career_path_item_links",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("activity", "활동"),
                            ("award", "수상·대회"),
                            ("portfolio", "작품"),
                            ("certification", "자격증"),
                        ],
                        max_length=20,
                        verbose_name="활동 유형",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="활동 제목")),
                (
                    "months",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="실행 월 목록",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="난이도",
                    ),
                ),
                (
                    "cost",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="비용"
                    ),
                ),
                (
                    "organizer",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="주최 기관"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, null=True, verbose_name="관련 URL"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="상세 설명"),
                ),
                (
                    "category_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="카테고리 태그",
                    ),
                ),
                (
                    "activity_subtype",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("project", "프로젝트"),
                            ("intern", "인턴"),
                            ("volunteer", "봉사"),
                            ("camp", "캠프"),
                            ("research", "연구"),
                            ("paper", "논문"),
                            ("general", "일반"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="활동 세부 유형",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="정렬 순서"),
                ),
            ],
            options={
                "verbose_name": "활동 항목",
                "verbose_name_plural": "활동 항목 목록",
                "db_table": "career_path_plan_items",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanYear",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grade_id", models.CharField(max_length=20, verbose_name="학년 ID")),
                (
                    "grade_label",
                    models.CharField(max_length=50, verbose_name="학년 라벨"),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("both", "1·2학기 통합"),
                            ("first", "1학기만"),
                            ("second", "2학기만"),
                            ("split", "1·2학기 분리"),
                            ("", "미선택"),
                        ],
                        default="both",
                        max_length=20,
                        verbose_name="학기 옵션",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="정렬 순서"),
                ),
            ],
            options={
                "verbose_name": "학년별 계획",
                "verbose_name_plural": "학년별 계획 목록",
                "db_table": "career_path_plan_years",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedPlan",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("private", "비공개"),
                            ("public", "전체 공유"),
                            ("school", "학교 공유"),
                            ("group", "그룹 공유"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="공유 유형",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="공유 설명"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="태그",
                    ),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "bookmark_count",
                    models.IntegerField(default=0, verbose_name="북마크 수"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="조회 수")),
                (
                    "comment_count",
                    models.IntegerField(default=0, verbose_name="댓글 수"),
                ),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="공유 일시"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="숨김 여부"),
                ),
            ],
            options={
                "verbose_name": "공유 커리어 패스",
                "verbose_name_plural": "공유 커리어 패스 목록",
                "db_table": "career_path_shared_plans",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedPlanGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "공유 패스-그룹 연결",
                "verbose_name_plural": "공유 패스-그룹 연결 목록",
                "db_table": "career_path_shared_plan_groups",
            },
        ),
        migrations.CreateModel(
            name="SubItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="하위 항목 제목"),
                ),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                (
                    "url",
                    models.URLField(blank=True, null=True, verbose_name="관련 URL"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="상세 설명"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="정렬 순서"),
                ),
            ],
            options={
                "verbose_name": "하위 실행 항목",
                "verbose_name_plural": "하위 실행 항목 목록",
                "db_table": "career_path_sub_items",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        # SQLite: template FK 인덱스 제거 후 필드 삭제
        migrations.RemoveIndex(
            model_name="templateyear",
            name="template_ye_templat_5861b7_idx",
        ),
        migrations.RemoveField(
            model_name="templateyear",
            name="template",
        ),
        migrations.RemoveIndex(
            model_name="usercareerpath",
            name="user_career_templat_8471f4_idx",
        ),
        migrations.RemoveField(
            model_name="usercareerpath",
            name="template",
        ),
        migrations.AlterUniqueTogether(
            name="schoolmember",
            unique_together=None,
        ),
        # SQLite: (school, role) 인덱스를 먼저 제거해야 school 필드 삭제 시 재작성 오류 방지
        migrations.RemoveIndex(
            model_name="schoolmember",
            name="school_memb_school__a8f7a6_idx",
        ),
        migrations.RemoveIndex(
            model_name="schoolmember",
            name="school_memb_user_id_8bd3cc_idx",
        ),
        migrations.RemoveField(
            model_name="schoolmember",
            name="school",
        ),
        migrations.RemoveField(
            model_name="schoolmember",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="templateitem",
            name="template_it_year_id_bdc290_idx",
        ),
        migrations.RemoveField(
            model_name="templateitem",
            name="year",
        ),
        migrations.RemoveIndex(
            model_name="usercareerpath",
            name="user_career_user_id_bfda79_idx",
        ),
        migrations.RemoveField(
            model_name="usercareerpath",
            name="user",
        ),
        migrations.RemoveIndex(
            model_name="school",
            name="schools_school__eef8c2_idx",
        ),
        migrations.RemoveIndex(
            model_name="school",
            name="schools_invite__9fa426_idx",
        ),
        migrations.RemoveField(
            model_name="school",
            name="invite_code",
        ),
        migrations.RemoveField(
            model_name="school",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="school",
            name="location",
        ),
        migrations.AddField(
            model_name="school",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                unique=True,
                verbose_name="학교 가입 코드",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="학교 설명"),
        ),
        migrations.AddField(
            model_name="school",
            name="grades",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="관리 학년 목록",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operated_schools",
                to=settings.AUTH_USER_MODEL,
                verbose_name="학교 운영자 (선생님)",
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="region",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="지역"
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="member_count",
            field=models.IntegerField(default=0, verbose_name="소속 학생 수"),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(max_length=200, verbose_name="학교 이름"),
        ),
        migrations.AlterField(
            model_name="school",
            name="school_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("elementary", "초등학교"),
                    ("middle", "중학교"),
                    ("high", "고등학교"),
                ],
                max_length=50,
                null=True,
                verbose_name="학교 유형",
            ),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["code"], name="idx_cp_schools_code"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(fields=["operator"], name="idx_cp_schools_operator"),
        ),
        migrations.AddIndex(
            model_name="school",
            index=models.Index(
                fields=["region", "school_type"], name="idx_cp_schools_region_type"
            ),
        ),
        migrations.AlterModelTable(
            name="school",
            table="career_path_schools",
        ),
        migrations.AddField(
            model_name="careerplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="소유자",
            ),
        ),
        migrations.AddField(
            model_name="planitem",
            name="goal_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="career_path.goalgroup",
                verbose_name="소속 목표 그룹",
            ),
        ),
        migrations.AddField(
            model_name="itemlink",
            name="plan_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="career_path.planitem",
                verbose_name="소속 활동",
            ),
        ),
        migrations.AddField(
            model_name="planyear",
            name="career_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="years",
                to="career_path.careerplan",
                verbose_name="소속 커리어 패스",
            ),
        ),
        migrations.AddField(
            model_name="planitem",
            name="plan_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="career_path.planyear",
                verbose_name="소속 학년",
            ),
        ),
        migrations.AddField(
            model_name="goalgroup",
            name="plan_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goal_groups",
                to="career_path.planyear",
                verbose_name="소속 학년",
            ),
        ),
        migrations.AddField(
            model_name="sharedplan",
            name="career_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_instances",
                to="career_path.careerplan",
                verbose_name="원본 커리어 패스",
            ),
        ),
        migrations.AddField(
            model_name="sharedplan",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shared_plans",
                to="career_path.school",
                verbose_name="소속 학교",
            ),
        ),
        migrations.AddField(
            model_name="sharedplan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_plans",
                to=settings.AUTH_USER_MODEL,
                verbose_name="공유자",
            ),
        ),
        migrations.AddField(
            model_name="sharedplangroup",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_path_shared_plan_links",
                to="community.group",
                verbose_name="그룹",
            ),
        ),
        migrations.AddField(
            model_name="sharedplangroup",
            name="shared_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_links",
                to="career_path.sharedplan",
                verbose_name="공유 패스",
            ),
        ),
        migrations.AddField(
            model_name="subitem",
            name="plan_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_items",
                to="career_path.planitem",
                verbose_name="소속 활동",
            ),
        ),
        migrations.DeleteModel(
            name="CareerPathTemplate",
        ),
        migrations.DeleteModel(
            name="SchoolMember",
        ),
        migrations.DeleteModel(
            name="TemplateItem",
        ),
        migrations.DeleteModel(
            name="TemplateYear",
        ),
    ]
