# Generated by Django 5.2.5 on 2026-03-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "career_path",
            "0002_careerplan_goalgroup_itemlink_planitem_planyear_and_more",
        ),
        ("community", "0002_remove_sharedroadmap_user_path_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserCareerPath",
        ),
        migrations.AddIndex(
            model_name="careerplan",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_cp_cplan_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="careerplan",
            index=models.Index(fields=["job_id"], name="idx_cp_cplan_job"),
        ),
        migrations.AddIndex(
            model_name="careerplan",
            index=models.Index(fields=["star_id"], name="idx_cp_cplan_star"),
        ),
        migrations.AddIndex(
            model_name="careerplan",
            index=models.Index(fields=["is_template"], name="idx_cp_cplan_template"),
        ),
        migrations.AddIndex(
            model_name="itemlink",
            index=models.Index(
                fields=["plan_item", "sort_order"], name="idx_cp_item_links_item_order"
            ),
        ),
        migrations.AddIndex(
            model_name="planyear",
            index=models.Index(
                fields=["career_plan", "sort_order"],
                name="idx_cp_plan_years_plan_order",
            ),
        ),
        migrations.AddIndex(
            model_name="planyear",
            index=models.Index(fields=["grade_id"], name="idx_cp_plan_years_grade"),
        ),
        migrations.AlterUniqueTogether(
            name="planyear",
            unique_together={("career_plan", "grade_id")},
        ),
        migrations.AddIndex(
            model_name="planitem",
            index=models.Index(
                fields=["plan_year", "sort_order"], name="idx_cp_plan_items_year_order"
            ),
        ),
        migrations.AddIndex(
            model_name="planitem",
            index=models.Index(
                fields=["goal_group"], name="idx_cp_plan_items_goal_group"
            ),
        ),
        migrations.AddIndex(
            model_name="planitem",
            index=models.Index(fields=["type"], name="idx_cp_plan_items_type"),
        ),
        migrations.AddIndex(
            model_name="planitem",
            index=models.Index(fields=["months"], name="idx_cp_plan_items_months"),
        ),
        migrations.AddIndex(
            model_name="goalgroup",
            index=models.Index(
                fields=["plan_year", "sort_order"], name="idx_cp_goal_groups_year_order"
            ),
        ),
        migrations.AddIndex(
            model_name="goalgroup",
            index=models.Index(
                fields=["semester_id"], name="idx_cp_goal_groups_semester"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedplan",
            index=models.Index(
                fields=["user", "-shared_at"], name="idx_cp_splan_user_shared"
            ),
        ),
        migrations.AddIndex(
            model_name="sharedplan",
            index=models.Index(fields=["career_plan"], name="idx_cp_splan_career_plan"),
        ),
        migrations.AddIndex(
            model_name="sharedplan",
            index=models.Index(fields=["school"], name="idx_cp_splan_school"),
        ),
        migrations.AddIndex(
            model_name="sharedplan",
            index=models.Index(fields=["share_type"], name="idx_cp_splan_share_type"),
        ),
        migrations.AddIndex(
            model_name="sharedplan",
            index=models.Index(fields=["-like_count"], name="idx_cp_splan_likes"),
        ),
        migrations.AddIndex(
            model_name="sharedplan",
            index=models.Index(fields=["-shared_at"], name="idx_cp_splan_shared"),
        ),
        migrations.AddIndex(
            model_name="sharedplan",
            index=models.Index(fields=["is_hidden"], name="idx_cp_splan_hidden"),
        ),
        migrations.AddIndex(
            model_name="sharedplangroup",
            index=models.Index(fields=["shared_plan"], name="idx_cp_spg_shared_plan"),
        ),
        migrations.AddIndex(
            model_name="sharedplangroup",
            index=models.Index(fields=["group"], name="idx_cp_spg_group"),
        ),
        migrations.AlterUniqueTogether(
            name="sharedplangroup",
            unique_together={("shared_plan", "group")},
        ),
        migrations.AddIndex(
            model_name="subitem",
            index=models.Index(
                fields=["plan_item", "sort_order"], name="idx_cp_sub_items_item_order"
            ),
        ),
        migrations.AddIndex(
            model_name="subitem",
            index=models.Index(fields=["is_done"], name="idx_cp_sub_items_done"),
        ),
    ]
