# Generated by Django 5.1 on 2026-03-25 13:37

import common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career_path', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='그룹명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('emoji', models.CharField(default='👥', max_length=10, verbose_name='이모지')),
                ('invite_code', models.CharField(default=common.utils.generate_invite_code, max_length=20, unique=True, verbose_name='초대 코드')),
                ('member_count', models.IntegerField(default=1, verbose_name='멤버 수')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '그룹',
                'verbose_name_plural': '그룹 목록',
                'db_table': 'groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', '관리자'), ('member', '멤버')], default='member', max_length=20, verbose_name='역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='community.group', verbose_name='그룹')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '그룹 멤버',
                'verbose_name_plural': '그룹 멤버 목록',
                'db_table': 'group_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedRoadmap',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('share_scope', models.CharField(choices=[('group', '그룹 공개'), ('public', '전체 공개')], default='group', max_length=20, verbose_name='공유 범위')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('bookmarks', models.IntegerField(default=0, verbose_name='북마크 수')),
                ('comments_count', models.IntegerField(default=0, verbose_name='댓글 수')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_roadmaps', to='community.group', verbose_name='그룹')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_roadmaps', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
                ('user_path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_roadmap', to='career_path.usercareerpath', verbose_name='사용자 패스')),
            ],
            options={
                'verbose_name': '공유 로드맵',
                'verbose_name_plural': '공유 로드맵 목록',
                'db_table': 'shared_roadmaps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapLike',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_rel', to='community.sharedroadmap', verbose_name='로드맵')),
            ],
            options={
                'verbose_name': '로드맵 좋아요',
                'verbose_name_plural': '로드맵 좋아요 목록',
                'db_table': 'roadmap_likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='댓글 내용')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.roadmapcomment', verbose_name='상위 댓글')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.sharedroadmap', verbose_name='로드맵')),
            ],
            options={
                'verbose_name': '로드맵 댓글',
                'verbose_name_plural': '로드맵 댓글 목록',
                'db_table': 'roadmap_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapBookmark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks_rel', to='community.sharedroadmap', verbose_name='로드맵')),
            ],
            options={
                'verbose_name': '로드맵 북마크',
                'verbose_name_plural': '로드맵 북마크 목록',
                'db_table': 'roadmap_bookmarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['creator'], name='groups_creator_17c824_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['invite_code'], name='groups_invite__7fda49_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_public'], name='groups_is_publ_4cdcd9_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['group', 'role'], name='group_membe_group_i_319a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmember',
            index=models.Index(fields=['user'], name='group_membe_user_id_88c209_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='sharedroadmap',
            index=models.Index(fields=['owner', '-created_at'], name='shared_road_owner_i_a20910_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedroadmap',
            index=models.Index(fields=['group', '-created_at'], name='shared_road_group_i_48fa29_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedroadmap',
            index=models.Index(fields=['share_scope'], name='shared_road_share_s_52712d_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedroadmap',
            index=models.Index(fields=['-likes'], name='shared_road_likes_6dace9_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaplike',
            index=models.Index(fields=['roadmap'], name='roadmap_lik_roadmap_06615b_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmaplike',
            index=models.Index(fields=['user'], name='roadmap_lik_user_id_37baa5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roadmaplike',
            unique_together={('roadmap', 'user')},
        ),
        migrations.AddIndex(
            model_name='roadmapcomment',
            index=models.Index(fields=['roadmap', 'created_at'], name='roadmap_com_roadmap_f5b42f_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmapcomment',
            index=models.Index(fields=['author'], name='roadmap_com_author__a3228f_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmapcomment',
            index=models.Index(fields=['parent'], name='roadmap_com_parent__dd38d3_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmapbookmark',
            index=models.Index(fields=['roadmap'], name='roadmap_boo_roadmap_995541_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmapbookmark',
            index=models.Index(fields=['user', '-created_at'], name='roadmap_boo_user_id_6794ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roadmapbookmark',
            unique_together={('roadmap', 'user')},
        ),
    ]
