# Generated by Django 5.2.5 on 2026-03-27 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "career_path",
            "0002_careerplan_goalgroup_itemlink_planitem_planyear_and_more",
        ),
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sharedroadmap",
            name="user_path",
        ),
        migrations.AddField(
            model_name="sharedroadmap",
            name="career_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="community_shared_roadmaps",
                to="career_path.careerplan",
                verbose_name="커리어 패스",
            ),
        ),
    ]
