# Generated by Django 5.1 on 2026-03-25 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('project', '프로젝트'), ('competition', '대회'), ('certification', '자격증'), ('activity', '활동'), ('research', '연구'), ('other', '기타')], default='project', max_length=50, verbose_name='항목 유형')),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(verbose_name='설명')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='기관/단체')),
                ('started_at', models.DateField(verbose_name='시작일')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('is_ongoing', models.BooleanField(default=False, verbose_name='진행 중')),
                ('url', models.URLField(blank=True, verbose_name='관련 URL')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('tags', models.JSONField(default=list, verbose_name='태그')),
                ('order_index', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '포트폴리오 항목',
                'verbose_name_plural': '포트폴리오 항목 목록',
                'db_table': 'portfolio_items',
                'ordering': ['user', 'order_index', '-started_at'],
                'indexes': [models.Index(fields=['user', 'item_type'], name='portfolio_i_user_id_d4fe28_idx'), models.Index(fields=['started_at'], name='portfolio_i_started_73b0f5_idx')],
            },
        ),
    ]
