# Generated by Django 5.1 on 2026-03-25 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('grade', models.CharField(choices=[('elementary_4', '초등학교 4학년'), ('elementary_5', '초등학교 5학년'), ('elementary_6', '초등학교 6학년'), ('middle_1', '중학교 1학년'), ('middle_2', '중학교 2학년'), ('middle_3', '중학교 3학년'), ('high_1', '고등학교 1학년'), ('high_2', '고등학교 2학년'), ('high_3', '고등학교 3학년'), ('university', '대학생'), ('graduate', '대학원생'), ('working', '직장인'), ('other', '기타')], default='middle_1', max_length=20, verbose_name='학년')),
                ('emoji', models.CharField(default='🧑\u200d🎓', max_length=10, verbose_name='프로필 이모지')),
                ('social_provider', models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver'), ('email', 'Email')], default='email', max_length=20, verbose_name='소셜 로그인 제공자')),
                ('social_uid', models.CharField(blank=True, max_length=255, verbose_name='소셜 UID')),
                ('profile_image_url', models.URLField(blank=True, verbose_name='프로필 이미지 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프 권한')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['social_provider', 'social_uid'], name='users_social__8d5789_idx'), models.Index(fields=['grade'], name='users_grade_871f3e_idx')],
            },
        ),
    ]
