# Generated by Django 5.1 on 2026-03-25 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiasecReport',
            fields=[
                ('riasec_type', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='RIASEC 타입')),
                ('type_name', models.CharField(max_length=50, verbose_name='타입 이름')),
                ('emoji', models.CharField(max_length=10, verbose_name='이모지')),
                ('tagline', models.CharField(max_length=100, verbose_name='태그라인')),
                ('description', models.TextField(verbose_name='설명')),
                ('strengths', models.JSONField(default=list, verbose_name='강점')),
                ('weaknesses', models.JSONField(default=list, verbose_name='약점')),
                ('career_keywords', models.JSONField(default=list, verbose_name='커리어 키워드')),
                ('recommended_activities', models.JSONField(default=list, verbose_name='추천 활동')),
                ('famous_people', models.JSONField(default=list, verbose_name='유명 인물')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='테마 색상')),
            ],
            options={
                'verbose_name': 'RIASEC 리포트',
                'verbose_name_plural': 'RIASEC 리포트 목록',
                'db_table': 'riasec_reports',
                'ordering': ['riasec_type'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('order_index', models.IntegerField(verbose_name='문제 순서')),
                ('zone', models.CharField(max_length=100, verbose_name='존 이름')),
                ('zone_icon', models.CharField(default='🎯', max_length=10, verbose_name='존 아이콘')),
                ('situation', models.CharField(max_length=200, verbose_name='상황')),
                ('description', models.TextField(verbose_name='문제 설명')),
                ('feedback_map', models.JSONField(default=dict, verbose_name='선택지별 피드백')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
            ],
            options={
                'verbose_name': '적성 검사 문제',
                'verbose_name_plural': '적성 검사 문제 목록',
                'db_table': 'quiz_questions',
                'ordering': ['order_index'],
                'indexes': [models.Index(fields=['order_index'], name='quiz_questi_order_i_3200b9_idx'), models.Index(fields=['is_active'], name='quiz_questi_is_acti_260010_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_key', models.CharField(max_length=10, verbose_name='선택지 키')),
                ('text', models.TextField(verbose_name='선택지 텍스트')),
                ('riasec_scores', models.JSONField(default=dict, verbose_name='RIASEC 점수')),
                ('order_index', models.IntegerField(verbose_name='선택지 순서')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.quizquestion', verbose_name='문제')),
            ],
            options={
                'verbose_name': '적성 검사 선택지',
                'verbose_name_plural': '적성 검사 선택지 목록',
                'db_table': 'quiz_choices',
                'ordering': ['question', 'order_index'],
                'indexes': [models.Index(fields=['question', 'order_index'], name='quiz_choice_questio_966c3a_idx')],
                'unique_together': {('question', 'choice_key')},
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('quick', '빠른 검사'), ('full', '전체 검사')], default='full', max_length=10, verbose_name='검사 모드')),
                ('answers', models.JSONField(default=list, verbose_name='답변 내역')),
                ('riasec_scores', models.JSONField(default=dict, verbose_name='RIASEC 점수')),
                ('top_type', models.CharField(max_length=2, verbose_name='1순위 타입')),
                ('second_type', models.CharField(blank=True, max_length=2, verbose_name='2순위 타입')),
                ('taken_at', models.DateTimeField(auto_now_add=True, verbose_name='응시 일시')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '적성 검사 결과',
                'verbose_name_plural': '적성 검사 결과 목록',
                'db_table': 'quiz_results',
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['user', '-taken_at'], name='quiz_result_user_id_2bb579_idx'), models.Index(fields=['top_type'], name='quiz_result_top_typ_b578c9_idx'), models.Index(fields=['mode'], name='quiz_result_mode_c49625_idx')],
            },
        ),
    ]
