# Generated by Django 5.1 on 2026-03-25 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('resource_type', models.CharField(choices=[('article', '아티클'), ('video', '비디오'), ('book', '책'), ('course', '강의'), ('tool', '도구'), ('other', '기타')], default='article', max_length=50, verbose_name='자료 유형')),
                ('url', models.URLField(verbose_name='URL')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='썸네일 URL')),
                ('tags', models.JSONField(default=list, verbose_name='태그')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resources', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
            ],
            options={
                'verbose_name': '학습 자료',
                'verbose_name_plural': '학습 자료 목록',
                'db_table': 'resources',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resource_type', 'is_active'], name='resources_resourc_dad69b_idx'), models.Index(fields=['-view_count'], name='resources_view_co_8f4841_idx')],
            },
        ),
    ]
