# Generated by Django 5.1 on 2026-03-25 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('todo', '할 일'), ('in_progress', '진행 중'), ('completed', '완료'), ('cancelled', '취소')], default='todo', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('urgent', '긴급')], default='medium', max_length=20, verbose_name='우선순위')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='진행률')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_plans', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '실행 계획',
                'verbose_name_plural': '실행 계획 목록',
                'db_table': 'execution_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='그룹명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('emoji', models.CharField(default='📋', max_length=10, verbose_name='이모지')),
                ('member_count', models.IntegerField(default=1, verbose_name='멤버 수')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plan_groups', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '계획 그룹',
                'verbose_name_plural': '계획 그룹 목록',
                'db_table': 'plan_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanGroupMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', '관리자'), ('member', '멤버')], default='member', max_length=20, verbose_name='역할')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='career_plan.plangroup', verbose_name='그룹')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '계획 그룹 멤버',
                'verbose_name_plural': '계획 그룹 멤버 목록',
                'db_table': 'plan_group_members',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('status', models.CharField(choices=[('todo', '할 일'), ('in_progress', '진행 중'), ('completed', '완료'), ('cancelled', '취소')], default='todo', max_length=20, verbose_name='상태')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='마감일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('order_index', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='career_plan.executionplan', verbose_name='실행 계획')),
            ],
            options={
                'verbose_name': '계획 항목',
                'verbose_name_plural': '계획 항목 목록',
                'db_table': 'plan_items',
                'ordering': ['plan', 'order_index'],
            },
        ),
        migrations.AddIndex(
            model_name='executionplan',
            index=models.Index(fields=['user', 'status'], name='execution_p_user_id_8f6284_idx'),
        ),
        migrations.AddIndex(
            model_name='executionplan',
            index=models.Index(fields=['due_date'], name='execution_p_due_dat_82b416_idx'),
        ),
        migrations.AddIndex(
            model_name='executionplan',
            index=models.Index(fields=['priority'], name='execution_p_priorit_382ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='plangroup',
            index=models.Index(fields=['creator'], name='plan_groups_creator_19386c_idx'),
        ),
        migrations.AddIndex(
            model_name='plangroupmember',
            index=models.Index(fields=['group', 'role'], name='plan_group__group_i_b53f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='plangroupmember',
            index=models.Index(fields=['user'], name='plan_group__user_id_08f83e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plangroupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['plan', 'status'], name='plan_items_plan_id_2abd9f_idx'),
        ),
        migrations.AddIndex(
            model_name='planitem',
            index=models.Index(fields=['due_date'], name='plan_items_due_dat_8fa4a6_idx'),
        ),
    ]
