# Generated by Django 5.2.5 on 2026-03-27 02:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_plan", "0001_initial"),
        ("community", "0002_remove_sharedroadmap_user_path_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planitem",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="plangroup",
            name="creator",
        ),
        # SQLite: unique_together와 인덱스를 먼저 제거
        migrations.AlterUniqueTogether(
            name="plangroupmember",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="plangroupmember",
            name="plan_group__group_i_b53f7e_idx",
        ),
        migrations.RemoveIndex(
            model_name="plangroupmember",
            name="plan_group__user_id_08f83e_idx",
        ),
        migrations.RemoveField(
            model_name="plangroupmember",
            name="group",
        ),
        migrations.RemoveField(
            model_name="plangroupmember",
            name="user",
        ),
        migrations.CreateModel(
            name="DreamResource",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("portfolio", "포트폴리오"),
                            ("guide", "가이드"),
                            ("template", "템플릿"),
                        ],
                        max_length=20,
                        verbose_name="자료 유형",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="자료 제목")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="자료 설명"),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, null=True, verbose_name="파일 URL"),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, null=True, verbose_name="썸네일 URL"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="태그"),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "bookmark_count",
                    models.IntegerField(default=0, verbose_name="북마크 수"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="다운로드 수"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="조회 수")),
                (
                    "comment_count",
                    models.IntegerField(default=0, verbose_name="댓글 수"),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("private", "비공개"),
                            ("public", "전체 공유"),
                            ("space", "그룹 공유"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="공유 유형",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="숨김 여부"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dream_resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "드림 자료",
                "verbose_name_plural": "드림 자료 목록",
                "db_table": "dream_resources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamSpace",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="프로그램 제목"),
                ),
                ("description", models.TextField(verbose_name="프로그램 설명")),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("class", "수업형"),
                            ("project", "프로젝트형"),
                            ("mentoring", "멘토링형"),
                        ],
                        max_length=20,
                        verbose_name="프로그램 유형",
                    ),
                ),
                (
                    "recruitment_status",
                    models.CharField(
                        choices=[("open", "모집중"), ("closed", "모집마감")],
                        default="open",
                        max_length=20,
                        verbose_name="모집 상태",
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="최대 참여자 수"
                    ),
                ),
                (
                    "current_participants",
                    models.IntegerField(default=0, verbose_name="현재 참여자 수"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="시작일"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="종료일"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dream_spaces",
                        to="community.group",
                        verbose_name="소속 그룹",
                    ),
                ),
            ],
            options={
                "verbose_name": "드림 스페이스",
                "verbose_name_plural": "드림 스페이스 목록",
                "db_table": "dream_spaces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceSection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="섹션 제목")),
                ("content", models.TextField(verbose_name="섹션 내용")),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="career_plan.dreamresource",
                        verbose_name="소속 자료",
                    ),
                ),
            ],
            options={
                "verbose_name": "자료 섹션",
                "verbose_name_plural": "자료 섹션 목록",
                "db_table": "resource_sections",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="로드맵 제목")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="로드맵 설명"),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("afterschool", "방과후"),
                            ("vacation", "방학"),
                            ("semester", "학기"),
                        ],
                        max_length=20,
                        verbose_name="실행 기간",
                    ),
                ),
                (
                    "star_color",
                    models.CharField(
                        default="#6C5CE7", max_length=20, verbose_name="적성 색상"
                    ),
                ),
                (
                    "focus_item_types",
                    models.JSONField(
                        blank=True, default=list, verbose_name="집중 활동 유형"
                    ),
                ),
                (
                    "final_result_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="최종 결과물 제목",
                    ),
                ),
                (
                    "final_result_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="최종 결과물 설명"
                    ),
                ),
                (
                    "final_result_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="최종 결과물 URL"
                    ),
                ),
                (
                    "final_result_image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="최종 결과물 이미지 URL"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmaps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "로드맵",
                "verbose_name_plural": "로드맵 목록",
                "db_table": "roadmaps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("activity", "활동"),
                            ("award", "수상·대회"),
                            ("project", "프로젝트"),
                            ("paper", "논문·연구"),
                        ],
                        max_length=20,
                        verbose_name="활동 유형",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="활동 제목")),
                (
                    "months",
                    models.JSONField(
                        blank=True, default=list, verbose_name="실행 월 목록"
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="난이도",
                    ),
                ),
                (
                    "target_output",
                    models.TextField(blank=True, null=True, verbose_name="목표 산출물"),
                ),
                (
                    "success_criteria",
                    models.TextField(blank=True, null=True, verbose_name="성공 기준"),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="career_plan.roadmap",
                        verbose_name="소속 로드맵",
                    ),
                ),
            ],
            options={
                "verbose_name": "로드맵 활동",
                "verbose_name_plural": "로드맵 활동 목록",
                "db_table": "roadmap_items",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapMilestone",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="마일스톤 제목"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="마일스톤 설명"
                    ),
                ),
                (
                    "month_week_label",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="월·주차 라벨",
                    ),
                ),
                (
                    "time_log",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="투입 시간"
                    ),
                ),
                (
                    "result_url",
                    models.URLField(blank=True, null=True, verbose_name="결과물 URL"),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="이미지 URL"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="기록 일시"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="career_plan.roadmap",
                        verbose_name="소속 로드맵",
                    ),
                ),
            ],
            options={
                "verbose_name": "로드맵 마일스톤",
                "verbose_name_plural": "로드맵 마일스톤 목록",
                "db_table": "roadmap_milestones",
                "ordering": ["sort_order", "-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapTodo",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "week_label",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="주차 라벨"
                    ),
                ),
                (
                    "week_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="주차 번호"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("goal", "목표"), ("task", "작업")],
                        default="task",
                        max_length=20,
                        verbose_name="항목 유형",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="TODO 제목")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="완료 여부"),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="메모")),
                (
                    "output_ref",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="산출물 참조",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="정렬 순서"),
                ),
                (
                    "roadmap_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="todos",
                        to="career_plan.roadmapitem",
                        verbose_name="소속 활동",
                    ),
                ),
            ],
            options={
                "verbose_name": "로드맵 TODO",
                "verbose_name_plural": "로드맵 TODO 목록",
                "db_table": "roadmap_todos",
                "ordering": ["week_number", "sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedDreamRoadmap",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("private", "비공개"),
                            ("public", "전체 공유"),
                            ("space", "그룹 공유"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="공유 유형",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="공유 설명"),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="태그"),
                ),
                (
                    "like_count",
                    models.IntegerField(default=0, verbose_name="좋아요 수"),
                ),
                (
                    "bookmark_count",
                    models.IntegerField(default=0, verbose_name="북마크 수"),
                ),
                ("view_count", models.IntegerField(default=0, verbose_name="조회 수")),
                (
                    "comment_count",
                    models.IntegerField(default=0, verbose_name="댓글 수"),
                ),
                (
                    "shared_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="공유 일시"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(default=False, verbose_name="숨김 여부"),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_instances",
                        to="career_plan.roadmap",
                        verbose_name="원본 로드맵",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_dream_roadmaps",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="공유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "공유 드림 로드맵",
                "verbose_name_plural": "공유 드림 로드맵 목록",
                "db_table": "shared_dream_roadmaps",
                "ordering": ["-shared_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedDreamRoadmapGroup",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_dream_roadmap_links",
                        to="community.group",
                        verbose_name="그룹",
                    ),
                ),
                (
                    "shared_roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_links",
                        to="career_plan.shareddreamroadmap",
                        verbose_name="공유 로드맵",
                    ),
                ),
            ],
            options={
                "verbose_name": "공유 드림 로드맵-그룹 연결",
                "verbose_name_plural": "공유 드림 로드맵-그룹 연결 목록",
                "db_table": "shared_dream_roadmap_groups",
            },
        ),
        migrations.CreateModel(
            name="SpaceParticipant",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "신청"),
                            ("approved", "승인"),
                            ("confirmed", "참여 확정"),
                            ("inProgress", "진행 체크"),
                        ],
                        default="applied",
                        max_length=20,
                        verbose_name="참여 상태",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청 일시"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="승인 일시"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="확정 일시"
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="career_plan.dreamspace",
                        verbose_name="소속 스페이스",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="space_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="참여자",
                    ),
                ),
            ],
            options={
                "verbose_name": "스페이스 참여자",
                "verbose_name_plural": "스페이스 참여자 목록",
                "db_table": "space_participants",
                "ordering": ["applied_at"],
            },
        ),
        migrations.DeleteModel(
            name="ExecutionPlan",
        ),
        migrations.DeleteModel(
            name="PlanItem",
        ),
        migrations.DeleteModel(
            name="PlanGroup",
        ),
        migrations.DeleteModel(
            name="PlanGroupMember",
        ),
        migrations.AddIndex(
            model_name="dreamresource",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_resources_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="dreamresource",
            index=models.Index(fields=["type"], name="idx_resources_type"),
        ),
        migrations.AddIndex(
            model_name="dreamresource",
            index=models.Index(fields=["share_type"], name="idx_resources_share_type"),
        ),
        migrations.AddIndex(
            model_name="dreamresource",
            index=models.Index(fields=["-like_count"], name="idx_resources_likes"),
        ),
        migrations.AddIndex(
            model_name="dreamspace",
            index=models.Index(fields=["group"], name="idx_spaces_group"),
        ),
        migrations.AddIndex(
            model_name="dreamspace",
            index=models.Index(fields=["program_type"], name="idx_spaces_program_type"),
        ),
        migrations.AddIndex(
            model_name="dreamspace",
            index=models.Index(
                fields=["recruitment_status"], name="idx_spaces_recruitment"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcesection",
            index=models.Index(
                fields=["resource", "sort_order"], name="idx_sections_order"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_roadmaps_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(fields=["period"], name="idx_roadmaps_period"),
        ),
        migrations.AddIndex(
            model_name="roadmapitem",
            index=models.Index(
                fields=["roadmap", "sort_order"], name="idx_roadmap_items_order"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmapitem",
            index=models.Index(fields=["type"], name="idx_roadmap_items_type"),
        ),
        migrations.AddIndex(
            model_name="roadmapmilestone",
            index=models.Index(
                fields=["roadmap", "sort_order"], name="idx_milestones_order"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmapmilestone",
            index=models.Index(fields=["-recorded_at"], name="idx_milestones_recorded"),
        ),
        migrations.AddIndex(
            model_name="roadmaptodo",
            index=models.Index(
                fields=["roadmap_item", "week_number"], name="idx_roadmap_todos_week"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmaptodo",
            index=models.Index(fields=["is_done"], name="idx_roadmap_todos_done"),
        ),
        migrations.AddIndex(
            model_name="shareddreamroadmap",
            index=models.Index(
                fields=["user", "-shared_at"], name="idx_shared_dream_rm_user"
            ),
        ),
        migrations.AddIndex(
            model_name="shareddreamroadmap",
            index=models.Index(fields=["roadmap"], name="idx_shared_dream_rm_roadmap"),
        ),
        migrations.AddIndex(
            model_name="shareddreamroadmap",
            index=models.Index(fields=["share_type"], name="idx_shared_dream_rm_type"),
        ),
        migrations.AddIndex(
            model_name="shareddreamroadmap",
            index=models.Index(
                fields=["-like_count"], name="idx_shared_dream_rm_likes"
            ),
        ),
        migrations.AddIndex(
            model_name="shareddreamroadmapgroup",
            index=models.Index(
                fields=["shared_roadmap"], name="idx_sdrg_shared_roadmap"
            ),
        ),
        migrations.AddIndex(
            model_name="shareddreamroadmapgroup",
            index=models.Index(fields=["group"], name="idx_sdrg_group"),
        ),
        migrations.AlterUniqueTogether(
            name="shareddreamroadmapgroup",
            unique_together={("shared_roadmap", "group")},
        ),
        migrations.AddIndex(
            model_name="spaceparticipant",
            index=models.Index(
                fields=["space", "status"], name="idx_participants_status"
            ),
        ),
        migrations.AddIndex(
            model_name="spaceparticipant",
            index=models.Index(fields=["user"], name="idx_participants_user"),
        ),
        migrations.AlterUniqueTogether(
            name="spaceparticipant",
            unique_together={("space", "user")},
        ),
    ]
