# Generated by Django 5.2.5 on 2026-04-01 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career_plan", "0004_shared_dream_comments_likes_bookmarks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roadmap",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "로드맵 (DreamMate 실행 계획)",
                "verbose_name_plural": "로드맵 목록 (DreamMate · /api/v1/career-plan/roadmaps/)",
            },
        ),
        migrations.CreateModel(
            name="ExecutionPlanAiUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "period_key",
                    models.CharField(
                        help_text="예: YYYY-MM (월별 한도)",
                        max_length=16,
                        verbose_name="집계 기간 키",
                    ),
                ),
                (
                    "call_count",
                    models.PositiveIntegerField(default=0, verbose_name="호출 횟수"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_plan_ai_usages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "실행계획 AI 사용량",
                "verbose_name_plural": "실행계획 AI 사용량",
                "db_table": "execution_plan_ai_usage",
                "indexes": [
                    models.Index(
                        fields=["user", "period_key"], name="idx_epai_user_period"
                    )
                ],
                "unique_together": {("user", "period_key")},
            },
        ),
    ]
